#!/usr/bin/env python3
"""Assemble maintainable page sources into the single-request ECU pages.

Large pages keep markup and JavaScript in focused source files under
data_src/pages/. The generated data_src/*.html files intentionally retain one
inline script: this avoids extra HTTP requests on the ECU access point and
keeps the existing browser/audit behavior deterministic.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data_src"
PAGES = SRC / "pages"

PAGE_MANIFEST = {
    "hardware.html": (
        "hardware.shell.html",
        (
            "hardware-pins.js",
            "hardware-state.js",
            "hardware-registry-catalog.js",
            "hardware-registry-view.js",
            "hardware-registry-actions.js",
            "hardware-dependencies.js",
            "hardware-validation.js",
            "hardware-save.js",
        ),
    ),
    "sequence.html": (
        "sequence.shell.html",
        (
            "sequence-definitions.js",
            "sequence-state.js",
            "sequence-editor.js",
            "sequence-runtime.js",
            "sequence-save.js",
        ),
    ),
    "config.html": (
        "config.shell.html",
        (
            "config-schema.js",
            "config-render.js",
            "config-validation-save.js",
            "config-runtime.js",
        ),
    ),
    "controllers.html": (
        "config.shell.html",
        (
            "config-schema.js",
            "config-render.js",
            "config-validation-save.js",
            "config-runtime.js",
        ),
    ),
    "system.html": (
        "config.shell.html",
        (
            "config-schema.js",
            "config-render.js",
            "config-validation-save.js",
            "config-runtime.js",
        ),
    ),
}

PLACEHOLDER = "<!-- OT_PAGE_SCRIPTS -->"
GENERATED_NOTE = (
    "<!-- GENERATED by tools/build_web_sources.py; edit data_src/pages/* instead. -->"
)


def assemble(output_name: str, shell_name: str, script_names: tuple[str, ...]) -> None:
    shell = (PAGES / shell_name).read_text(encoding="utf-8")
    surface = Path(output_name).stem
    if shell_name == "config.shell.html":
        effective_surface = "system" if surface == "system" else "controllers"
        heading = "System" if effective_surface == "system" else "Controllers"
        shell = shell.replace("<title>OpenTurbine — Config</title>",
                              f"<title>OpenTurbine — {heading}</title>")
        shell = shell.replace('class="ot-nav-controllers"',
                              'class="active ot-nav-controllers"' if effective_surface == "controllers"
                              else 'class="ot-nav-controllers"')
        shell = shell.replace('class="ot-nav-system"',
                              'class="active ot-nav-system"' if effective_surface == "system"
                              else 'class="ot-nav-system"')
        shell = shell.replace('<h1 class="cfg-workspace-title">Configuration</h1>',
                              f'<h1 class="cfg-workspace-title">{heading}</h1>')
        shell = shell.replace('placeholder="Search limits, oil, relight, N2, telemetry…"',
                              'placeholder="Search ECU runtime and display settings…"' if effective_surface == "system"
                              else 'placeholder="Search outputs, limits, oil, relight, N2…"')
    if shell.count(PLACEHOLDER) != 1:
        raise RuntimeError(f"{shell_name} must contain exactly one {PLACEHOLDER}")
    scripts = []
    for name in script_names:
        body = (PAGES / name).read_text(encoding="utf-8").rstrip()
        if shell_name == "config.shell.html" and effective_surface != "system":
            body = re.sub(
                r"\n?// OT_SYSTEM_ONLY_BEGIN\n.*?// OT_SYSTEM_ONLY_END\n?",
                "\n",
                body,
                flags=re.DOTALL,
            ).rstrip()
        if shell_name == "config.shell.html" and effective_surface == "system":
            body = re.sub(
                r"\n?// OT_CONTROLLERS_ONLY_BEGIN\n.*?// OT_CONTROLLERS_ONLY_END\n?",
                "\n",
                body,
                flags=re.DOTALL,
            ).rstrip()
        scripts.append(f"// Source: data_src/pages/{name}\n{body}")
    surface_bootstrap = ""
    if shell_name == "config.shell.html":
        effective_surface = "system" if surface == "system" else "controllers"
        surface_bootstrap = f"window.OT_CONFIG_SURFACE='{effective_surface}';\n"
    inline = "<script>\n" + surface_bootstrap + "\n\n".join(scripts) + "\n</script>"
    generated = shell.replace(PLACEHOLDER, inline)
    if not generated.startswith(GENERATED_NOTE):
        generated = GENERATED_NOTE + "\n" + generated
    output = SRC / output_name
    old = output.read_text(encoding="utf-8") if output.exists() else None
    if old != generated:
        output.write_text(generated, encoding="utf-8", newline="\n")
        print(f"  assembled {output_name}")


def main() -> None:
    for output_name, (shell_name, scripts) in PAGE_MANIFEST.items():
        assemble(output_name, shell_name, scripts)


if __name__ == "__main__":
    main()
